{
 "title": "xApp",
 "time": { "from": "2026-03-06T16:56:18.311Z", "to": "2026-03-06T19:14:55.209Z" },
 "panels": [
  {
   "title": "xApp latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "xapp_inference_latency_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"alex-app\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"alex-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(\n  container_memory_working_set_bytes{pod=\"nfstream-pod\", container!=\"\", container!=\"POD\"} \n  / \n  container_spec_memory_limit_bytes{pod=\"nfstream-pod\", container!=\"\", container!=\"POD\"}\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}