{
 "title": "xApp",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "xApp latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(xapp_inference_latency_ms_sum[1m]) / rate(xapp_inference_latency_ms_count[1m])",
     "legendFormat": "Average"
    },
    {
     "expr": "histogram_quantile(0.95, rate(xapp_inference_latency_ms_bucket[1m]))",
     "legendFormat": "P95 Latency"
    },
    {
     "expr": "histogram_quantile(0.99, rate(xapp_inference_latency_ms_bucket[1m]))",
     "legendFormat": "P99 Latency"
    }
   ]
  },
  {
   "title": "xApp Flow Rate (per min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(xapp_flows_total[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "xApp CPU process usage as % of total CPU)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"alex-app\"}[1m])*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container RAM Usage (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(\n  container_memory_working_set_bytes{pod=\"nfstream-pod\", container!=\"\", container!=\"POD\"} \n  / \n  container_spec_memory_limit_bytes{pod=\"nfstream-pod\", container!=\"\", container!=\"POD\"}\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}