{
 "title": "xApp",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "xApp latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(xapp_inference_latency_ms_sum[1m]) / rate(xapp_inference_latency_ms_count[1m])",
     "legendFormat": "Average"
    },
    {
     "expr": "histogram_quantile(0.95, rate(xapp_inference_latency_ms_bucket[1m]))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, rate(xapp_inference_latency_ms_bucket[1m]))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "xApp Flow Rate (per min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(xapp_flows_total[1m]) * 60",
     "legendFormat": "Flow Rate"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"alexxapp\", pod=\"nfstream-pod\", container=\"\"}[1m])) by (pod)",
     "legendFormat": "CPU Usage (%)"
    }
   ]
  },
  {
   "title": "Container RAM Usage (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"alexxapp\", pod=\"nfstream-pod\", container=\"\"}) by (pod) / 1024 / 1024",
     "legendFormat": "RAM Usage"
    }
   ]
  }
 ]
}