apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
  namespace: alexxapp
  labels:
    app: hello-world
spec:
  hostNetwork: true
  containers:
  - name: hello-world
    image: hello-world
    command: []
  restartPolicy: Never