apiVersion: v1
kind: Pod
metadata:
  name: nfstream-pod
  namespace: nfstream
spec:
  initContainers:
  - name: hello-world-test
    image: hello-world # use the Docker provided one
    command: [ ]
  containers:
  - name: nfstream
    image: alextlittle/nfstream-ml-app:v2
    imagePullPolicy: Always
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    securityContext:
      privileged: true