apiVersion: v1
kind: Pod
metadata:
  name: nfstream-pod
  namespace: alexxapp
  labels:
    app: nfstream
spec:
  initContainers:
  - name: hello-world-test
    image: hello-world # use the Docker provided one
    command: []
  containers:
  - name: xapp
    image: alextlittle/nfstream-ml-app:v2
    imagePullPolicy: Never
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    securityContext:
      privileged: true
    ports:
      - containerPort: 8000
    # limit container size to 1cpu and 2gb ram
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: nfstream-service
  namespace: alexxapp
spec:
  selector:
    app: nfstream
  ports:
  - port: 8000
    targetPort: 8000